### ISSUE TITLE
add foreign key fk_authitem_parent CDbCommand failed to execute the SQL statement

### ISSUE THREAD

**Issue by Marat** [schmunk42/p3admin#1]
> add foreign key fk_authitem_parent: AuthItemChild (parent) references authitem (name) ...exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1005 Can't create table 'p3_html_2011_10_16_02_51.#sql-41f_1e8' (errno: 150). The SQL statement executed was: ALTER TABLE `AuthItemChild` ADD CONSTRAINT `fk_authitem_parent` FOREIGN KEY (`parent`) REFERENCES `authitem` (`name`)' in /var/www/framework/framework/db/CDbCommand.php:336
> Stack trace:
> # 0 /var/www/framework/framework/db/CDbCommand.php(1350): CDbCommand->execute()
> # 1 /var/www/framework/framework/db/CDbMigration.php(342): CDbCommand->addForeignKey('fk_authitem_par...', 'AuthItemChild', 'parent', 'authitem', 'name', NULL, NULL)
> # 2 /var/www/html_2011_10_16_02_51/protected/modules/p3admin/modules-install/rights/migrations/m110402_195159_init.php(61): CDbMigration->addForeignKey('fk_authitem_par...', 'AuthItemChild', 'parent', 'authitem', 'name', NULL, NULL)
> # 3 /var/www/framework/framework/cli/commands/MigrateCommand.php(363): m110402_195159_init->up()
> # 4 /var/www/framework/framework/cli/commands/MigrateCommand.php(100): MigrateCommand->migrateUp('m110402_195159_...')
> # 5 [internal function]: MigrateCommand->actionUp(Array)
> # 6 /var/www/framework/framework/console/CConsoleCommand.php(135): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
> # 7 /var/www/framework/framework/console/CConsoleCommandRunner.php(63): CConsoleCommand->run(Array)
> # 8 /var/www/framework/framework/console/CConsoleApplication.php(88): CConsoleCommandRunner->run(Array)
> # 9 /var/www/framework/framework/base/CApplication.php(158): CConsoleApplication->processRequest()
> # 10 /var/www/framework/framework/yiic.php(33): CApplication->run()
> # 11 /var/www/html_2011_10_16_02_51/protected/yiic.php(7): require_once('/var/www/framew...')
> # 12 /var/www/html_2011_10_16_02_51/protected/yiic(4): require_once('/var/www/html_2...')
> # 13 {main}

file p3admin\modules-install\rights\migrations\m111013_235000_p3items.php

7   -       $this->insert("AuthItem", array(
8   -           "name" => "Editor",
9   -           "type" => "2",
10 -            "description" => "Content Editor (Widgets, Media Files)",
11 -            "bizrule" => null,
12 -            "data" => "N;",
13 -        ));

23 +        $this->insert("AuthItem", array(
24 +            "name" => "Editor",
25 +            "type" => "2",
26 +            "description" => "Content Editor (Widgets, Media Files)",
27 +            "bizrule" => null,
28 +            "data" => "N;",
29 +        ));

**Comment by schmunk42** [comment]
Can you provide more details about the system where the error occured?
PHP version, MySQL version, Phundament 3 version, installation via yiic or p3 web-interface?
Looks like there was a problem with foreign keys, but I couldn't reproduce it.
Thanks!

**Comment by Marat** [comment]
[www]# php -v
PHP 5.3.2 (cli) (built: Jun 25 2011 08:12:19)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

[www]# cat /etc/redhat-release
CentOS Linux release 6.0 (Final)

[ www]# uname -a -m -p
Linux c6 2.6.32-71.29.1.el6.i686 #1 SMP Mon Jun 27 18:07:00 BST 2011 i686 i686 i386 GNU/Linux

mysql 5.1.52

**Comment by Marat** [comment]
Phundament 3 latest from git

**Comment by schmunk42** [comment]
Is this about the same problem?
http://www.yiiframework.com/forum/index.php?/topic/24696-extension-phundament/page__view__findpost__p__120416

Something is going wrong with the foreign keys, but I can't tell it yet.

Do you also have an error with fk for 'p3_media'?

**Comment by Marat** [comment]
we have a table structure

 / / Schema for table 'AuthAssignment'

 $ this-> createTable ("AuthAssignment", array (
 "itemname" => "varchar (64) NOT NULL",
 "userid" => "varchar (64) NOT NULL",
 "bizrule" => "text",
 "data" => "text",
 / / "INDEX (itemname)"
 ), $ Options);

 / / Data for table 'AuthAssignment'
 / / Schema for table 'AuthItem'

 $ this-> createTable ("AuthItem", array (
 "name" => "varchar (64) NOT NULL",
 "type" => "int (11) NOT NULL",
 "description" => "text",
 "bizrule" => "text",
 "data" => "text",
 "PRIMARY KEY (name)"
 ), $ Options);

 and we want to add keys
 if ((Yii:: app () -> db-> schema instanceof CSqliteSchema) == false):
 $ this-> addForeignKey ('fk_authitem_parent', 'AuthItemChild', 'parent', 'authitem', 'name', null, null); / / update 'null' for ON DELTE and ON UPDATE
 $ this-> addForeignKey ('fk_authitem_child', 'AuthItemChild', 'child', 'authitem', 'name', null, null); / / update 'null' for ON DELTE and ON UPDATE
 endif;

 but more correct to write

 if ((Yii:: app () -> db-> schema instanceof CSqliteSchema) == false):
 $ this-> addForeignKey ('fk_authitem_parent', 'AuthItemChild', 'parent', 'AuthItem', 'name', null, null); / / update 'null' for ON DELTE and ON UPDATE
 $ this-> addForeignKey ('fk_authitem_child', 'AuthItemChild', 'child', 'AuthItem', 'name', null, null); / / update 'null' for ON DELTE and ON UPDATE
 endif;

// Foreign Keys for table 'AuthAssignment'

if ((Yii::app()->db->schema instanceof CSqliteSchema) == false):
$this->addForeignKey('fk_authitem_itemname', 'AuthAssignment', 'itemname', 'AuthItem', 'name', null, null); // update 'null' for ON DELTE and ON UPDATE
endif;

Linux files 'authitem' and 'AuthItem' different

and migration

 $ this-> insert ("AuthAssignment", array (
 "itemname" => "Editor",
 "userid" => "3",
 "bizrule" => null,
 "data" => "N;",
 ));

 $ this-> insert ("AuthItem", array (
 "name" => "Editor",
 "type" => "2",
 "description" => "Content Editor (Widgets, Media Files)",
 "bizrule" => null,
 "data" => "N;",
 ));

 to be

 $ this-> insert ("AuthItem", array (
 "name" => "Editor",
 "type" => "2",
 "description" => "Content Editor (Widgets, Media Files)",
 "bizrule" => null,
 "data" => "N;",
 ));

 $ this-> insert ("AuthAssignment", array (
 "itemname" => "Editor",
 "userid" => "3",
 "bizrule" => null,
 "data" => "N;",
 ));

 because we have the key

 $ this-> addForeignKey ('fk_authitem_itemname', 'AuthAssignment', 'itemname', 'AuthItem', 'name', null, null);

and we can not create a key element in a non-existent

sorry for bad eng

**Comment by schmunk42** [comment]
Thanks, I hope this will fix it ... no tests yet.
https://github.com/schmunk42/p3admin/commit/6c6ee52b11eea3b94a87fa510658351f1937dbef

**Comment by schmunk42** [comment]
tested on Linux MySQL with latest rev from master
